const ColorBoxStyles = {
  root: {
    width: "20%",
    height: "25%",
    margin: "0 auto",
    display: "inline-block",
    position: "relative",
    cursor: "pointer",
    marginBottom: "-3.9px",
    "&:hover button": {
        opacity: 1,
        transition: "0.4s",
    },
  },
  copyButton: {
    width: "100px",
    height: "32px",
    position: "absolute",
    top: "50%",
    left: "50%",
    marginTop: "-16px",
    marginLeft: "-50px",
    textAlign: "center",
    outline: "none",
    background: " rgba(255, 255, 255, 0.3)",
    fontSize: "1rem",
    lineHeight: "30px",
    color: "white",
    textTransform: "uppercase",
    border: "none",
    borderRadius: "5px",
    opacity: 0,
  },
  boxContent: {
    position: "absolute",
    width: "100%",
    left: 0,
    bottom: 0,
    padding: "8px",
    color: "black",
    textTransform: "uppercase",
    letterSpacing: "1px",
    fontSize: "12px",
  },
  more: {
    display: "inline-block",
    background: "rgba(255, 255, 255, 0.3)",
    position: "absolute",
    border: "none",
    right: 0,
    bottom: 0,
    color: "white",
    width: "52px",
    height: "26px",
    fontSize: "13px",
    textAlign: "center",
    lineHeight: "26px",
    textTransform: "uppercase",
    letterSpacing: "0.7px",
    cursor: "pointer",
  },
  copiedOverlay: {
    opacity: 0,
    zIndex: 0,
    height: "100%",
    width: "100%",
    transition: "transform 0.7s ease-in-out",
    transform: "scale(0.01)",
    "&.copied": {
      opacity: 1,
      transform: "scale(50)",
      zIndex: 3,
      position: "absolute",
    },
  },
  copiedText: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    position: "fixed",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    zIndex: 0,
    opacity: 0,
    color: "#cccccc",
    transform: "scale(0.1)",
    "&.copied": {
      opacity: 1,
      transform: "scale(3)",
      zIndex: 4,
      transition: "all 0.2s ease-in-out 0.2s",
    },
    "& h2": {
      width: "100%",
      padding: "5px",
      backgroundColor: "#ffffff48",
      textAlign: "center",
      textTransform: "uppercase",
      lineHeight: "30px",
    },
    "& p": {
      marginTop: "5px",
      fontSize: "0.5em",
    },
  },
};
export default ColorBoxStyles;